version: "2"
services:
  # app:
  #   container_name: chatbot
  #   restart: always
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - mongodb
  #   environment:
  #     - DEBUG=VNTK.*
  #     - BD_HOST=mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - /usr/local/mongodb:/data/db
    ports:
      - "27017:27017"
